#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flyLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           flyRight,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	bool flyBackwards = false;

	while (true)
	{
		// If Btn8U is pressed at any time, it ends all of this.
		if (Btn8U == true)
			stopAllTasks();

		// Basic tank drive.
		motor[frontLeft] = vexRT[Ch3];
		motor[backLeft] = vexRT[Ch3];
		motor[frontRight] = vexRT[Ch2];
		motor[backRight] = vexRT[Ch2];

		/*
		Ok, so I realize that this code is really strange. Let me boil it down for you, mein Freund.

		Because Jared had to make his flywheel the way he did, I can't safely test both motors at once. If one
		motor is going forward and the other backwards, then it could break something. This code is designed
		to be able to test both motors safely.

		If Btn5U is being held down, then the left flywheel motor will run. If Btn6U is being held down, then
		the right flywheel motor will run.
		If Btn7D is being held down, then the motor will run backwards. If it is not held down, then it runs
		forwards.

		This compiles, so of course it will work flawlessly without any bugs or breakage.

		REALLY FREAKING IMPORTANT: DON'T HOLD DOWN BOTH BTN7D AND BTN6D!
		*/

		flyBackwards = Btn7D;

		if (Btn5U == true)
		{
			switch(flyBackwards)
			{
				case true:
					motor[flyLeft] = -63;
					break;
				case false:
					motor[flyLeft] = 63;
					break;
			}
		}
		else if (Btn6U == true)
		{
			switch(flyBackwards)
			{
				case true:
					motor[flyRight] = -63;
					break;
				case false:
					motor[flyRight] = 63;
					break;
			}
		}
		else
		{
			motor[flyLeft] = 0;
			motor[flyRight] = 0;
		}

	}

}
